### ISSUE TITLE
Match scollbar colour for Dark / Material theme

### ISSUE THREAD

**Issue by kjunggithub** [yakyak/yakyak#559]
After the 1.4.2. update, I noticed how the scrollbar is now visible for the left conversations panel. The default white scrollbar colour is rather off putting for the dark / material themes.

Most likely to do with this style?
```css
.applayout > .left > .list {
    overflow-y: scroll;
}
```

Not sure if this was a design change or something left behind but I would love for it to be not visible and if you keep it visible, at least have the scrollbar match the themes colours.
